### ISSUE TITLE
Fitting isotopic ratios

### ISSUE THREAD

**Issue by advaitmehla** [TSFitPy-developers/TSFitPy#73]
Hi,

We are interested in using TSFitPy for estimating isotopic fractions of Oxygen in Hydrogen-deficient Carbon (HdC) stars (these have an unusually high abundance of 18O) by using 12C16O and 12C18O lines in high resolution IR spectra. 

We have a very sparse grid of specially computed stellar models for HdC stars that I was able to get working with TSFitPy and and successfully find N and O abundances with. In the current fitting modes, the isotopic ratio of elements is a fixed parameter - I was able to get around this by simply setting 16O to 1.0 while fitting 12C16O lines, and similarly for 12C18O lines, giving me the 16O and 18O abundances that I can then use to find the ratios and total [O].

The issue with this method is that we currently only have models with a single oxygen abundance value of 8.8, and this is problematic in some cases. If the 16O/18O ratio is >>1, say ~10, then we have stars where [16O] is roughly around the model abundance but [18O] is 1 dex lower. With large deviations from the input abundance, the fitted values are less reliable, which means that the [18O] value we get here is likely erroneous. It would be much better to fit the overall abundance and isotopic ratio simultaneously to avoid this problem.

Is this something that has been considered for implementation by your team in the past? If you have any ideas or pointers for how something like this could be achieved, I could try developing a custom fitting mode that does this. I think this would be very different from the currently implemented methods because each line can no longer be fitted independently - I would have to come up with something that simultaneously optimizes two sets of linemasks. I'm also unsure about how we could define uncertainties in fitted parameters in this case. We have less than 10 stars where this could be an issue, so I'm also open to more brute force approaches as long as they can give us good fits and sensible error estimates.

Let me know if you have any thoughts on this.

**Comment by stormnick** [comment]
Hi,

Sorry for the late reply - was on a vacation.

I haven't worked closely with isotopic ratios much, but please correct me if I misunderstood any steps in your process:

- Instead of MARCS models, you use your custom 1D model atmospheres that were computed with a constant A(O) = 8.8.
- You use your custom IR linelist with 12C16O and 12C18O lines, with 2 separate linemasks (one for 16O and another for 18O molecular lines)
- You fit these two separately, by first setting isotopic ratio of 16O = 1.0 and 18O = 0.0 (in `solar_isotopes.py` I presume?), and fitting the 12C16O line. Then you do the same for 18O, by setting isotopic ratios 16O = 0.0 and 18O = 1.0. Is that correct?
- This gives your separate 16O and 18O abundances, which you can use to compare 16O/18O. Right?

Fitting two linemasks simultaneously is not hard: there is already a mode called "all" that does that. Alternatively, you could also create a big linemask that contains both 16O and 18O. In my opinion as a quick check (i.e. as a bruteforce), you could try to fit both linemasks at the same time, but by varying the isotopic ratios in steps of say 0.2. You could see which isotopic ratio gives you the best fit simultaneously. I think if this method doesn't work, then I see no reason why fitting both abundance and isotopic ratio at once would work.

Based on my personal experience, I do not recommend to fit both parameters at the same time anyway, simply because fitting algorithm struggles to do that well. I have the same problem when fitting FeH and vmic simultaneously. It is either very slow (I mean time taken to fit one line goes from 3 min to like 1 hour) or inaccurate. 

Let me know.

**Comment by advaitmehla** [comment]
Thanks for the response! Yes, your understanding of the process I've been using so far is exactly right. 

Using the "all" mode seems like a great idea! I have a feeling a single big linemask may not work very well, as we do have blending from a lot of CN lines which could also influence the chi^2 values and possibly affect the fitting process. Doing this with individual line masks for 12C16O and 12C18O sounds like it might work nicely.

I am indeed modifying isotopic ratios through `solar_isotopes.py` - could you suggest a simple way to make it so I could supply this information through the fitlist itself? That way I could simply have one row for each individual run with a different set of ratios, making it far easier to launch a batch of runs even for a large set of ratios.

> Based on my personal experience, I do not recommend to fit both parameters at the same time anyway, simply because fitting algorithm struggles to do that well. I have the same problem when fitting FeH and vmic simultaneously. It is either very slow (I mean time taken to fit one line goes from 3 min to like 1 hour) or inaccurate.

This makes sense, and I did observe this being an issue myself. Doing things manually seems best.

**Comment by stormnick** [comment]
One thing to note is that at some point I did notice that the mode `all` might skip some lines during the synthesis (see the issue here: https://trello.com/c/Xt6O6vpI/38-windowsflag-seems-to-remove-some-lines )? If that's true, then it is a TurboSpectrum bug, not TSFitPy one. I am not too sure if that is still the case, but I thought to mention it in case if you see anything weird during the fits.

> Using the "all" mode seems like a great idea! I have a feeling a single big linemask may not work very well, as we do have blending from a lot of CN lines which could also influence the chi^2 values and possibly affect the fitting process. Doing this with individual line masks for 12C16O and 12C18O sounds like it might work nicely.

While it is true that the O abundance would affect CN slightly, I am actually not too sure about the overall impact on the fit. It depends on the distance between 16O and 18O lines as well... 

> I am indeed modifying isotopic ratios through solar_isotopes.py - could you suggest a simple way to make it so I could supply this information through the fitlist itself? That way I could simply have one row for each individual run with a different set of ratios, making it far easier to launch a batch of runs even for a large/fine ratio grid.

Sadly there is no way to do that right now. I simply had no need for that so far. You could probably find a way to "hard code" it. `turbospectrum_class_nlte.py:562` takes individual isotopes from `self.free_isotopes`, which can be set beforehand. So you could change it here (or earlier when it passed in `TSFitPy:py:984`, by predefining `your_custom_free_isotopes` and adding `free_isotopes=your_custom_free_isotopes` in the `spectrumclass.configure()`). But perhaps see if it works at all by fitting both linemasks together in the first place?

**Comment by JGerbs13** [comment]
For a little background on the solar_isotopes.py list, it was added when I
wanted to generate some models with different isotopes to allow the isotope
ratios to be more easily adjusted. One of our goals is to eventually add
the ability to fit isotopes, but as Nick said, we just haven't had the need
yet. I know a colleague who has set something up to change the isotopes
file in between fitting steps to do something similar to what Nick
mentioned. I could ask them what they did if it would be helpful.

**Comment by advaitmehla** [comment]
> Sadly there is no way to do that right now. I simply had no need for that so far. You could probably find a way to "hard code" it. turbospectrum_class_nlte.py:562 takes individual isotopes from self.free_isotopes, which can be set beforehand. So you could change it here (or earlier when it passed in TSFitPy:py:984, by predefining your_custom_free_isotopes and adding free_isotopes=your_custom_free_isotopes in the spectrumclass.configure()). But perhaps see if it works at all by fitting both linemasks together in the first place?

Thanks, that makes sense - I was just wondering if it would be straightforward to make some tweaks to enable that myself, but I'll try and do it manually as a start to see if it works like you said.

>I know a colleague who has set something up to change the isotopes
file in between fitting steps to do something similar to what Nick
mentioned. I could ask them what they did if it would be helpful.

@JGerbs13 It would be very helpful if you could ask them!

**Comment by advaitmehla** [comment]
I gave things a shot, and they seemed to have worked well. The star in question appears to have a higher 16O/18O ~ 5 from the results. This makes the 12C18O lines too weak and nearly always blended with 12C16O and CN lines, so I went with the option of choosing larger regions that include strong-ish lines of this mixed with other molecules. 

Other parts of the spectrum have strong, unblended CN and 12C16O lines (with 16O fraction set to 1.0), so I fit these first using lbl method to constrain abundances. I used results from the former as input to the 'all' mode fits, and the latter just as a sanity check to see if 'all' returns sensible values for 16O. I got A(16O) = 8.798 +/- 0.139 from this - the error is standard deviation of the line-by-line scatter.

After defining regions of interests for 'all' mode, I manually varied the 16O/18O ratio through `solar_isotopes.py` over a range of 3.5-7.0. Here is a plot of chi^2 v/s ratios that I obtained:

![image](https://github.com/user-attachments/assets/d5c4ce8b-0a9f-408d-b16f-0691eab0a690)

This clearly indicates the correct ratio is around ~5.0. Now, I computed the 16O abundances using the total O value and ratios from these runs, and got the following plot:

![image](https://github.com/user-attachments/assets/1a0746d9-41f1-4be0-ab29-00f6c8997596)

The red line is the fitted value, and dashed lines are +/- sigma bounds on it. So at 5.0 (and above it), we do see a recovered [16O] abundance that looks consistent with my attempt to fit only [16O].

I'd say this is a success! Do you think it would be possible to recover some confidence intervals for the ratio from this exercise? I was thinking about using the usual chi squared critical value table to map a deviation of some amount in chi^2 to, say 1 sigma error bars, but I think with the modified chi^2 metric you use, this would not be applicable directly. Let me know your thoughts on this.

I'll also think more on how to make it easier to do this with a large amount of ratios, because doing it manually is indeed quite cumbersome.

**Comment by stormnick** [comment]
Nice, seems good!

I am not too certain about confidence intervals. `lbl` and `all` methods have different ways of calculations of chi-squared. 'lbl' method's calculation is described here: https://github.com/TSFitPy-developers/TSFitPy/blob/main/docs/tsfitpy_doc.pdf . You could probably convert chi squared for `all` method to the similar one as the `lbl`. 

One other thing I think might be worth a try: could you try to refit abundance for ratio of say 5.0 or 6.0 in Figure 1? Like 10-20 times (just do the same spectra in `fitlist` 10-20 times)? This is to see how much chi2 varies. Since it is a numerical method and the starting value is randomised a bit, the output will not always be exactly the same. It should be pretty close (since I tried to set convergence limit quite low), but for your own sake I would double check it.

**Comment by JGerbs13** [comment]
Looks like good progress! The scripts my colleague had are for an older
version of TSFitPy, so it looks like you may be better off just continuing
with what you have already.

**Comment by advaitmehla** [comment]
> One other thing I think might be worth a try: could you try to refit abundance for ratio of say 5.0 or 6.0 in Figure 1? Like 10-20 times (just do the same spectra in fitlist 10-20 times)? This is to see how much chi2 varies. Since it is a numerical method and the starting value is randomised a bit, the output will not always be exactly the same. It should be pretty close (since I tried to set convergence limit quite low), but for your own sake I would double check it.

Good point - I tried this and the spread is signficant but not too bad - at 5.0, I'm getting a standard deviation of 0.043 in chi2 over 20 runs, which looks like this:

![image](https://github.com/user-attachments/assets/57925d80-d6d0-4006-b6aa-4a95411fd894)

Spread in total Oxygen abundance is much smaller, at 0.004 dex.

> I am not too certain about confidence intervals. lbl and all methods have different ways of calculations of chi-squared. 'lbl' method's calculation is described here: https://github.com/TSFitPy-developers/TSFitPy/blob/main/docs/tsfitpy_doc.pdf . You could probably convert chi squared for all method to the similar one as the lbl.

I looked at the function being minimized in the `all` mode, and its actually the sum of squares of relative differences at the moment (`chi_square += np.sum(np.square((flux_line_obs - flux_line_mod)) / flux_line_mod)`), so I definitely can't expect it to behave like a chi2 distribution and extract confidence intervals from it. For `lbl`, its using reduced chi square, which also would need to be converted to chi square to do this and can't be used directly. I would imagine changing the function/metric being minimized in `all` mode would not be practical, as I would have to tweak a lot of parameters and sensitivities to get it to converge nicely? 

Instead, I was thinking of changing it so that it simply prints/saves the final "regular" chi^2 value that I compute on my own with a function I make. That way, it does not influence the actual optimization and just gives me this extra number that I want. I think this would be pretty easy to do by modifying `calc_chi_sqr_all_mode` at `TSFitPy.py:2490`, right? I could just add another key to `intermediate_results` I think, and print it out in every iteration. Not sure about adding to the output  file though.

> The scripts my colleague had are for an older
version of TSFitPy, so it looks like you may be better off just continuing
with what you have already.

Oh okay, thanks for checking!
