### ISSUE TITLE
Near-Infrared linelist

### ISSUE THREAD

**Issue by danangsetyo5364** [TSFitPy-developers/TSFitPy#74]
Hello! I am interested in your program, and I would like to analyze high-resolution Near-IR spectra. 

For the line lists in IR region, I already have linelists from VALD, however the format, I think little bit different with the linelist use in your code. So do we need to reformat the linelist? Or do you have any suggestions regarding that?

Thanks!

**Comment by stormnick** [comment]
Hi,

Technically speaking, this is more of a question to TurboSpectrum (TS): https://github.com/bertrandplez/Turbospectrum_NLTE , because that's the actual code that uses the linelist. The TS code only uses TS-formatted linelists. I do not have a converter from VALD to TS format, sadly. I know that Nikolai Piskunov had a FORTRAN converter from VALD to TS linelist. I don't have it myself, but I know that when someone tried using it, they ran into some issues during the conversion. Maybe you could try asking him and see if it works for you?

While converting most columns from VALD to TS is straight forward, there are some specific weird cases. That's why I haven't written one yet. Otherwise, I can only point you towards APOGEE TS-formatted IR linelist (15000-17000 AA).

**Comment by danangsetyo5364** [comment]
Alright. Thanks! I already solved the problem.

**Comment by stormnick** [comment]
Thanks @JGerbs13 , I didn't actually know about that one. I tried running the converter (from here btw: https://github.com/bertrandplez/Turbospectrum_NLTE/blob/master/Utilities/vald3turbo.f ) and it worked great on the long format VALD. I will keep that in mind for the future, sorry for the misinformation initially!
